tsana_app_name: maga
tsana_api_endpoint: https://stock-exp2-api.azurewebsites.net
series_limit: 5000000
models_in_training_limit_per_instance: 1
maga_service_endpoint: http://52.250.33.25:56789
az_storage_account: tsana
az_storage_account_key: K8wgcBGfq/gRmiPJLAIpW3wTr1IbmfAtbdYP5jPAcrCireE/55r5Z0cchi7bHV8fJL2+oMXvauPUQ2vBUpwpZw==
az_tsana_meta_table: modelmeta
az_tsana_moniter_table: moniter
az_tsana_model_blob_connection: DefaultEndpointsProtocol=https;AccountName=tsana;AccountKey=K8wgcBGfq/gRmiPJLAIpW3wTr1IbmfAtbdYP5jPAcrCireE/55r5Z0cchi7bHV8fJL2+oMXvauPUQ2vBUpwpZw==;EndpointSuffix=core.windows.net
model_temp_dir: temp
model_data_dir: data
training_owner_life: 60