tsana_app_name: forecast
series_limit: 5000000
models_in_training_limit_per_instance: 1
az_tsana_meta_table: modelmeta
az_tsana_moniter_table: moniter
model_temp_dir: temp
model_data_dir: data
training_owner_life: 60
lstm:
  num_hidden: 32
  batch_size: 50
  validation_ratio: 0.3
  validation_freq: 2
  steps_per_epoc: 100
  train_history_step: 730
  epoc: 3